In [1]:
#Rainfall prediction in Australia

In [2]:
#importing libraries
import pandas as pd
import numpy as np

In [3]:
#Reading csv file
df=pd.read_csv("weatherAUS.csv.csv")
print(df.head(10))

         Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   
5  2008-12-06   Albury     14.6     29.7       0.2          NaN       NaN   
6  2008-12-07   Albury     14.3     25.0       0.0          NaN       NaN   
7  2008-12-08   Albury      7.7     26.7       0.0          NaN       NaN   
8  2008-12-09   Albury      9.7     31.9       0.0          NaN       NaN   
9  2008-12-10   Albury     13.1     30.1       1.4          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1     

In [4]:
#Considering only those rows that are necessary
x=df.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
y=df.iloc[:,-1].values

In [5]:
print (x)#independent data

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]


In [6]:
print(y)#dependent data

['No' 'No' 'No' ... 'No' 'No' nan]


In [7]:
y=y.reshape(-1,1)
print(y)#changing 1D list into 2D

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 [nan]]


In [8]:
#dealing with null values/invalid data
#using sklearn.impute
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
x=imputer.fit_transform(x)
y=imputer.fit_transform(y)
print(x)
print(y)#all nan values will be replayed by most frequent value 

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 20.0 ... 15.0 20.9 'No']]
[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [9]:
#encoding: convert string/character in numerical form
from sklearn.preprocessing import LabelEncoder
lev1=LabelEncoder()
x[:,0]=lev1.fit_transform(x[:,0]) #this will work on column 1 (location) 
lev2=LabelEncoder()
x[:,4]=lev2.fit_transform(x[:,4])#this will work on column 4(WindGusDir)
lev3=LabelEncoder()
x[:,6]=lev3.fit_transform(x[:,6])#this will work on colum 6(WindDir9am)
lev4=LabelEncoder()
x[:,7]=lev4.fit_transform(x[:,7])#this will work on colum 6(WindDir3pm)
lev5=LabelEncoder()
x[:,-1]=lev5.fit_transform(x[:,-1])#this will work on last column of x(Rain today)
lev6=LabelEncoder()
y=lev6.fit_transform(y)#this will work on y 

C:\New folder\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
print(x)
print(y)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]
 [41 14.9 20.0 ... 15.0 20.9 0]]
[0 0 0 ... 0 0 0]


In [11]:
#Feature scaling 
#we want the data in a definite range to imporve training
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
#we do not need to do it with y as it is already in range
print(x)

[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


In [12]:
# Splitting the dataset into Training set and Test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train)
print(y_train)

[[ 0.22535368  1.03946939  0.07140543 ...  0.68369032  0.08145488
  -0.52979545]
 [ 1.42012717 -0.45263203  0.11369237 ... -0.41722163  0.22733303
  -0.52979545]
 [ 0.50647685 -0.20133073 -0.14002932 ... -0.06058818 -0.02065982
   1.88752093]
 ...
 [ 1.0687232   0.75675544  0.93124006 ...  1.10234698  1.07342629
  -0.52979545]
 [ 0.57675765 -0.04426743 -0.16822062 ...  0.01694083 -0.28324049
   1.88752093]
 [ 1.63096955 -0.0285611  -0.91529006 ... -0.35519842 -0.76463838
  -0.52979545]]
[1 0 0 ... 0 0 0]


In [13]:
#Training Model
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=150,random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=150, random_state=0)

In [14]:
classifier.score(x_train,y_train)

0.9999398460057748

In [15]:
y_pred=classifier.predict(x_test)
print(y_pred)

[0 0 0 ... 0 0 0]


In [16]:
y_pred=lev6.inverse_transform(y_pred)
print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [17]:
y_test=lev6.inverse_transform(y_test)
print(y_test)

['Yes' 'Yes' 'No' ... 'Yes' 'No' 'No']


In [18]:
y_test=y_test.reshape(-1,1)
y_pred=y_pred.reshape(-1,1)

In [19]:
df1=np.concatenate((y_test,y_pred),axis=1)#vertical
dataframe=pd.DataFrame(df1,columns=['Rainfall on tomorrow','Prediction of Rainfall'])


In [20]:
print(df1)

[['Yes' 'No']
 ['Yes' 'No']
 ['No' 'No']
 ...
 ['Yes' 'No']
 ['No' 'No']
 ['No' 'No']]


In [21]:
print(dataframe)

      Rainfall on tomorrow Prediction of Rainfall
0                      Yes                     No
1                      Yes                     No
2                       No                     No
3                       No                    Yes
4                       No                     No
...                    ...                    ...
29087                   No                    Yes
29088                   No                     No
29089                  Yes                     No
29090                   No                     No
29091                   No                     No

[29092 rows x 2 columns]


In [22]:
#Calculating accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8538086071772308